# Generated by Django 3.1.4 on 2020-12-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('dated_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.dated')),
                ('amount', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='', max_length=500)),
            ],
            bases=('bot.dated',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('dated_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.dated')),
                ('books', models.JSONField(default=list)),
            ],
            bases=('bot.dated',),
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('dated_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.dated')),
                ('delivery_phone', models.CharField(default='+000000000000', max_length=20)),
                ('delivery_name', models.CharField(default='', max_length=100)),
                ('post_service', models.CharField(default='', max_length=300)),
                ('delivery_address', models.CharField(default='', max_length=300)),
            ],
            bases=('bot.dated',),
        ),
        migrations.CreateModel(
            name='ViberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_id', models.CharField(default='1234567890A==', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('convers_answers_data', models.JSONField(default=dict)),
                ('bills', models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bot.bill')),
                ('orders', models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bot.order')),
                ('requisites', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.requisites')),
            ],
        ),
    ]
