# Generated by Django 3.1.4 on 2021-01-04 12:27

import BooksDelivery.model_fields.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201230_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='convers_answers_data',
            field=BooksDelivery.model_fields.json.OrderedJSONField(default='\\{\\}'),
        ),
    ]
