# Generated by Django 3.1.5 on 2021-03-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210105_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='dated_ptr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dated_ptr',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='dated_ptr',
        ),
        migrations.AddField(
            model_name='bill',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisites',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dated',
        ),
    ]
